async_mode: threaded
cache:
  base_dir: cache
  type: file
chunks:
  group_by_columns:
  - id
  overlap: 64
  size: 512
claim_extraction:
  description: Any claims or facts that could be relevant to information discovery.
  max_gleanings: 0
  prompt: /mnt/i/ComfyUI/input/IF_AI/presets/claim_extraction.json
cluster_graph:
  max_cluster_size: 10
community_report:
  max_input_length: 8000
  max_length: 2000
  prompt: /mnt/i/ComfyUI/input/IF_AI/presets/community_report.json
embed_graph:
  enabled: false
embeddings:
  async_mode: threaded
  batch_max_tokens: 8191
  batch_size: 16
  llm:
    api_base: http://localhost:11434/v1
    api_key: <API_KEY>
    concurrent_requests: 10
    model: nomic-embed-text
    type: openai_embedding
encoding_model: cl100k_base
entity_extraction:
  entity_types:
  - organization
  - person
  - geo
  - event
  max_gleanings: 0
  prompt: /mnt/i/ComfyUI/input/IF_AI/presets/entity_extraction.json
global_search:
  concurrency: 32
  data_max_tokens: 12000
  map_max_tokens: 1000
  max_tokens: 12000
  reduce_max_tokens: 2000
input:
  base_dir: /mnt/i/ComfyUI/output/IF_AI/knowledge_base
  file_encoding: utf-8
  file_pattern: .*\.(txt|pdf)$
  file_type: text
  type: file
llm:
  api_base: http://localhost:11434/v1
  api_key: ${OLLAMA_API_KEY}
  concurrent_requests: 10
  max_tokens: 4096
  model: impactframes/dolphin_llama3_omost:latest
  model_supports_json: true
  temperature: 0.0
  top_p: 1.0
  type: openai_chat
local_search:
  community_prop: 0.1
  conversation_history_max_turns: 5
  llm_max_tokens: 2000
  max_tokens: 12000
  text_unit_prop: 0.5
  top_k_entities: 10
  top_k_relationships: 10
parallelization:
  num_threads: 50
  stagger: 0.3
reporting:
  base_dir: output/${timestamp}/reports
  type: file
skip_workflows: []
snapshots:
  graphml: true
  parquet: true
  raw_entities: true
  top_level_nodes: true
storage:
  base_dir: output/${timestamp}/artifacts
  type: file
summarize_descriptions:
  max_length: 500
  prompt: /mnt/i/ComfyUI/input/IF_AI/presets/summarize_descriptions.json
umap:
  enabled: false
